[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'enter_build_env.ps1')

function Show-Tool {
    param([Parameter(Mandatory = $true)][string]$Name, [string[]]$Arguments = @('--version'))
    $command = Get-Command $Name -ErrorAction SilentlyContinue
    if (-not $command) {
        Write-Host "[FAIL] $Name not found" -ForegroundColor Red
        return $false
    }
    Write-Host "[ OK ] $Name -> $($command.Source)"
    & $command.Source @Arguments 2>&1 | Select-Object -First 3 | ForEach-Object { "       $_" }
    return ($LASTEXITCODE -eq 0)
}

$ok = $true
foreach ($tool in @('flutter', 'dart', 'rustc', 'cargo', 'rustfmt', 'flutter_rust_bridge_codegen', 'cmake', 'ninja', 'java', 'adb', 'sdkmanager', 'cl', 'link')) {
    $ok = (Show-Tool $tool) -and $ok
}

Write-Host "[INFO] cargo-ndk"
& cargo ndk --version 2>&1 | Select-Object -First 3 | ForEach-Object { "       $_" }
$ok = ($LASTEXITCODE -eq 0) -and $ok

$requiredPackages = @(
    (Join-Path $env:ANDROID_HOME 'platform-tools'),
    (Join-Path $env:ANDROID_HOME 'platforms\android-32'),
    (Join-Path $env:ANDROID_HOME 'platforms\android-35'),
    (Join-Path $env:ANDROID_HOME 'platforms\android-36'),
    (Join-Path $env:ANDROID_HOME 'build-tools\28.0.3'),
    (Join-Path $env:ANDROID_HOME 'build-tools\30.0.2'),
    (Join-Path $env:ANDROID_HOME 'build-tools\35.0.0'),
    (Join-Path $env:ANDROID_HOME 'cmake\3.22.1'),
    (Join-Path $env:ANDROID_HOME 'ndk\25.2.9519653')
)
foreach ($path in $requiredPackages) {
    if (Test-Path -LiteralPath $path -PathType Container) {
        Write-Host "[ OK ] package $path"
    } else {
        Write-Host "[FAIL] package missing $path" -ForegroundColor Red
        $ok = $false
    }
}

$windowsArtifacts = @(
    (Join-Path $env:JM3_BUILD_ROOT 'windows\rust.h'),
    (Join-Path $env:JM3_BUILD_ROOT 'windows\rust.lib')
)
foreach ($path in $windowsArtifacts) {
    if (Test-Path -LiteralPath $path -PathType Leaf) {
        Write-Host "[ OK ] Windows Rust artifact $path"
    } else {
        Write-Host "[INFO] Windows Rust artifact will be generated by scripts/build_windows.ps1: $path" -ForegroundColor Yellow
    }
}

Write-Host "[INFO] Rust metadata"
& cargo metadata --manifest-path (Join-Path $env:JM3_BUILD_ROOT 'rust-backend\rust\Cargo.toml') --no-deps --format-version 1 | Out-Null
if ($LASTEXITCODE -eq 0) { Write-Host '[ OK ] cargo metadata' } else { Write-Host '[FAIL] cargo metadata' -ForegroundColor Red; $ok = $false }

Write-Host '[INFO] flutter doctor -v'
& flutter doctor -v
if ($LASTEXITCODE -ne 0) {
    Write-Host '[WARN] flutter doctor reported issues; see the section above.' -ForegroundColor Yellow
}

if (-not $ok) { exit 1 }
Write-Host 'Build environment checks passed.' -ForegroundColor Green
